apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meditrack-staging-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: meditrack.staging.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-fastapi
                port:
                  number: 80
