apiVersion: v1
data:
  APP_SECRET_KEY: cmVwbGFjZV93aXRoX3JhbmRvbV9zZWNyZXQ=
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXMuZ3BieHd5ZHZleGljdGJqd3JqZmc6bWVkaXRhbXBhZmxyQGF3cy0xLWFwLXNvdXRoLTEucG9vbGVyLnN1cGFiYXNlLmNvbTo2NTQzL3Bvc3RncmVzP3NzbD1yZXF1aXJl
  ELASTICSEARCH_PASSWORD: ""
  ELASTICSEARCH_USERNAME: ""
  GEMINI_API_KEY: ""
  KEYCLOAK_CLIENT_SECRET: cmVwbGFjZS13aXRoLXN0YWdpbmctY2xpZW50LXNlY3JldA==
  OPENAI_API_KEY: ""
  SUPABASE_ANON_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1kd1luaDNlV1IyWlhocFkzUmlhbmR5YW1abklpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTnpRNU16VTJOVFVzSW1WNGNDSTZNakE1TURVeE1UWTFOWDAuRGhjVWNWcDh1SGRkT3dKakRBVmNhUDZSbjV1RlJabGVzZTR1b1NhQ2w2RQ==
  SUPABASE_SERVICE_ROLE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1kd1luaDNlV1IyWlhocFkzUmlhbmR5YW1abklpd2ljbTlzWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMzTkRrek5UWTFOU3dpWlhod0lqb3lNRGt3TlRFeE5qVTFmUS5aa2VHVmdwN1hHVFNiQmhTbld3amVuT3h2bmJsTXNQcWRQRzcxVjQ0QTZz
  SUPABASE_URL: aHR0cHM6Ly9ncGJ4d3lkdmV4aWN0Ymp3cmpmZy5zdXBhYmFzZS5jbw==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"APP_SECRET_KEY":"cmVwbGFjZV93aXRoX3JhbmRvbV9zZWNyZXQ=","DATABASE_URL":"cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXMuZ3BieHd5ZHZleGljdGJqd3JqZmc6bW\nVkaXRhbXBhZmxyQGF3cy0xLWFwLXNvdXRoLTEucG9vbGVyLnN1cGFiYXNlLmNvbTo2NTQz\nL3Bvc3RncmVzP3NzbD1yZXF1aXJl\n","ELASTICSEARCH_PASSWORD":"","ELASTICSEARCH_USERNAME":"","GEMINI_API_KEY":"","KEYCLOAK_CLIENT_SECRET":"cmVwbGFjZS13aXRoLXN0YWdpbmctY2xpZW50LXNlY3JldA==","OPENAI_API_KEY":"","SUPABASE_ANON_KEY":"ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQm\nhZbUZ6WlNJc0luSmxaaUk2SW1kd1luaDNlV1IyWlhocFkzUmlhbmR5YW1abklpd2ljbTlz\nWlNJNkltRnViMjRpTENKcFlYUWlPakUzTnpRNU16VTJOVFVzSW1WNGNDSTZNakE1TURVeE\n1UWTFOWDAuRGhjVWNWcDh1SGRkT3dKakRBVmNhUDZSbjV1RlJabGVzZTR1b1NhQ2w2RQ==\n","SUPABASE_SERVICE_ROLE_KEY":"ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQm\nhZbUZ6WlNJc0luSmxaaUk2SW1kd1luaDNlV1IyWlhocFkzUmlhbmR5YW1abklpd2ljbTlz\nWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMzTkRrek5UWTFOU3dpWlhod0\nlqb3lNRGt3TlRFeE5qVTFmUS5aa2VHVmdwN1hHVFNiQmhTbld3amVuT3h2bmJsTXNQcWRQ\nRzcxVjQ0QTZz\n","SUPABASE_URL":"aHR0cHM6Ly9ncGJ4d3lkdmV4aWN0Ymp3cmpmZy5zdXBhYmFzZS5jbw=="},"kind":"Secret","metadata":{"annotations":{},"labels":{"variant":"staging"},"name":"staging-fastapi-secrets","namespace":"meditrack-staging"},"type":"Opaque"}
  creationTimestamp: "2026-03-31T09:55:26Z"
  labels:
    variant: staging
  name: staging-fastapi-secrets
  namespace: meditrack-staging
  resourceVersion: "9318"
  uid: 06e0436e-e86c-4f12-b969-e4e929b98cb9
type: Opaque
